# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        ('persona', '__first__'),
        ('municipio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='municipio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipio.Municipio'),
        ),
        migrations.AddField(
            model_name='administradores',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
    ]
