# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsAdmin', '0011_administrador_root'),
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='administrador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Administrador'),
            preserve_default=False,
        ),
    ]
