# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(upload_to='noticias/'),
        ),
    ]
