# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsAdmin', '0012_marcador'),
        ('noticias', '0003_auto_20170510_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='interes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Interes'),
            preserve_default=False,
        ),
    ]
