# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='root',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.Persona')),
                ('idroot', models.IntegerField()),
            ],
            bases=('persona.persona',),
        ),
    ]
