# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.TextField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('fecha_incripcion', models.DateField()),
                ('prioridad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('solicitud', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('sexo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generos.Genero')),
            ],
        ),
    ]
