# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_persona_intereses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_incripcion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='prioridad',
            field=models.IntegerField(null=True),
        ),
    ]
