# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoCuenta', models.BooleanField(default=True)),
                ('municipio', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Administradores',
                'verbose_name': 'Administrador',
            },
        ),
    ]
