# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsAdmin', '0002_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Interes',
                'verbose_name_plural': 'Intereses',
            },
        ),
        migrations.CreateModel(
            name='ListaSolicitudesAdministrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluada', models.BooleanField(default=False)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Administrador')),
            ],
            options={
                'verbose_name': 'Lista de solicitudes del Administrador',
                'verbose_name_plural': 'Lista de solicitudes del Administrador',
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoCuenta', models.BooleanField(default=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Administrador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Usuario')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
            },
        ),
    ]
