# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsAdmin', '0003_interes_listasolicitudesadministrador_suscriptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaInteresAdministrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Administrador')),
                ('interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Interes')),
            ],
            options={
                'verbose_name': 'Lista de intereses de Administradores',
                'verbose_name_plural': 'Lista de intereses de Administradores',
            },
        ),
        migrations.CreateModel(
            name='ListaInteresSuscriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Interes')),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Suscriptor')),
            ],
            options={
                'verbose_name': 'Lista de intereses de Suscriptores',
                'verbose_name_plural': 'Lista de intereses de Suscriptores',
            },
        ),
        migrations.CreateModel(
            name='ListaSolicitudesSuscriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluada', models.BooleanField(default=False)),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Suscriptor')),
            ],
            options={
                'verbose_name': 'Lista de solicitudes del Suscriptor',
                'verbose_name_plural': 'Lista de solicitudes del Suscriptores',
            },
        ),
    ]
