# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsAdmin', '0004_listainteresadministrador_listainteressuscriptor_listasolicitudessuscriptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Usuario')),
            ],
            options={
                'verbose_name': 'Usuario Root',
                'verbose_name_plural': 'Usuarios Root',
            },
        ),
    ]
