# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsAdmin', '0005_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2017, 4, 24, 17, 31, 42, 278482)),
        ),
    ]
