# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsAdmin', '0006_auto_20170424_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
