# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsAdmin', '0007_auto_20170424_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=100),
        ),
    ]
