# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsAdmin', '0008_auto_20170424_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='listasolicitudesadministrador',
            name='suscriptor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Suscriptor'),
            preserve_default=False,
        ),
    ]
