# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsAdmin', '0010_remove_listasolicitudesadministrador_suscriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='root',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Root'),
            preserve_default=False,
        ),
    ]
