# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsAdmin', '0013_auto_20170520_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modelsAdmin.Municipio'),
            preserve_default=False,
        ),
    ]
